# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OverrideFunc | Just past default
email: pdanielleonard+OF@gmail.com
description: >
 Daniel Leonard: iOS Developer, Swift on Lunix, Open Source -> JSQMessagesViewController, Twitter nut.
url: https://macmedan.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: macmedan
github_username:  macmedan

facebook: https://www.facebook.com/overridefunc
twitter: macmedan
copyrights-owner: MacMeDan # Copyright in the footer

# Build settings
markdown: kramdown
destination: ./_site
kramdown:
   input: GFM
   syntax_highlighter: rouge

authors:
      MacMeDan:
        display_name: Dan Leonard
        email: mailto:pdanielleonard+OF@gmail.com
        web: http://overridefunc.com/
        facebook: https://www.facebook.com/overridefunc
        twitter: https://twitter.com/macmedan
        github: https://github.com/macmedan/
        gravatar: 'https://s.gravatar.com/avatar/28c884619263d70e274669742eb645a2?s=80'

analytics: 'UA-88807386-1'
theme: minima
gems: [jekyll-sitemap, jekyll-paginate, jekyll-seo-tag, jekyll-feed]

exclude:
  - Gemfile
  - Gemfile.lock
