
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site
title: OverrideFunc
url: https://macmedan.github.io
description: Just past default
img_url: /assets

facebook: https://www.facebook.com/overridefunc
copyrights-owner: Dan Leonard # Copyright in the footer

# Build settings
markdown: kramdown
destination: ./_site
kramdown:
   input: GFM
   syntax_highlighter: rouge

author:
  name: Dan Leonard
  email: mailto:pdanielleonard+overridefunc@gmail.com
  web: http://overridefunc.com/
  facebook: https://www.facebook.com/overridefunc
  twitter: https://twitter.com/macmedan
  github: https://github.com/macmedan
  gravatar: 'https://s.gravatar.com/avatar/28c884619263d70e274669742eb645a2?s=80'

analytics: 'UA-88807386-1'
theme: minima

gems: [jekyll-sitemap, jekyll-paginate, jekyll-seo-tag, jekyll-feed]

# plugins_dir:
#     - jekyll-paginate
#     - jekyll-sitemap

exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, assets/, package.json, yarn.lock, scripts/]
